// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: annotations.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClaimAnnotations = `-- name: CountClaimAnnotations :one
select count(*) from claim_annotations where model = $1 and prompt_version = $2
`

type CountClaimAnnotationsParams struct {
	Model         string
	PromptVersion string
}

func (q *Queries) CountClaimAnnotations(ctx context.Context, arg CountClaimAnnotationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClaimAnnotations, arg.Model, arg.PromptVersion)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listClaimsMissingAnnotation = `-- name: ListClaimsMissingAnnotation :many
select c.id, c.claim_text, c.match_id
from claims c
where not exists (
    select 1 from claim_annotations ca
    where ca.claim_id = c.id and ca.model = $1 and ca.prompt_version = $2
)
order by c.id
`

type ListClaimsMissingAnnotationParams struct {
	Model         string
	PromptVersion string
}

type ListClaimsMissingAnnotationRow struct {
	ID        int64
	ClaimText string
	MatchID   int64
}

func (q *Queries) ListClaimsMissingAnnotation(ctx context.Context, arg ListClaimsMissingAnnotationParams) ([]ListClaimsMissingAnnotationRow, error) {
	rows, err := q.db.Query(ctx, listClaimsMissingAnnotation, arg.Model, arg.PromptVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClaimsMissingAnnotationRow
	for rows.Next() {
		var i ListClaimsMissingAnnotationRow
		if err := rows.Scan(&i.ID, &i.ClaimText, &i.MatchID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertClaimAnnotation = `-- name: UpsertClaimAnnotation :one
insert into claim_annotations (
    claim_id, model, prompt_version, claim_type, concepts, subject_athlete_id,
    arm, temporality, certainty, raw_payload
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
on conflict (claim_id, model, prompt_version) do update
set claim_type = excluded.claim_type,
    concepts = excluded.concepts,
    subject_athlete_id = excluded.subject_athlete_id,
    arm = excluded.arm,
    temporality = excluded.temporality,
    certainty = excluded.certainty,
    raw_payload = excluded.raw_payload
returning id
`

type UpsertClaimAnnotationParams struct {
	ClaimID          int64
	Model            string
	PromptVersion    string
	ClaimType        string
	Concepts         []string
	SubjectAthleteID pgtype.Int8
	Arm              pgtype.Text
	Temporality      string
	Certainty        string
	RawPayload       []byte
}

func (q *Queries) UpsertClaimAnnotation(ctx context.Context, arg UpsertClaimAnnotationParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertClaimAnnotation,
		arg.ClaimID,
		arg.Model,
		arg.PromptVersion,
		arg.ClaimType,
		arg.Concepts,
		arg.SubjectAthleteID,
		arg.Arm,
		arg.Temporality,
		arg.Certainty,
		arg.RawPayload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
