// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Athlete struct {
	ID            int64
	CanonicalName string
	CreatedAt     pgtype.Timestamptz
}

type Claim struct {
	ID                 int64
	SourceID           int64
	MatchID            int64
	ClaimText          string
	TimestampSeconds   pgtype.Int4
	Speaker            pgtype.Text
	Confidence         pgtype.Text
	Relevance          pgtype.Text
	ObservedAt         pgtype.Timestamptz
	ExtractedAt        pgtype.Timestamptz
	ExtractionModel    pgtype.Text
	RawPayload         []byte
	CreatedAt          pgtype.Timestamptz
	SourceExtractionID pgtype.Int8
}

type ClaimSubject struct {
	ClaimID   int64
	AthleteID int64
}

type EvalFold struct {
	ProtocolID    int64
	FoldIndex     int32
	TrainMatchIds []int64
	TestMatchIds  []int64
}

type EvalProtocol struct {
	ID        int64
	Name      string
	Kind      string
	CreatedAt pgtype.Timestamptz
	Spec      []byte
}

type Event struct {
	ID        int64
	Slug      string
	Promoter  string
	Name      string
	HeldOn    pgtype.Date
	CreatedAt pgtype.Timestamptz
}

type ExperimentRun struct {
	ID            int64
	GitSha        string
	GitDirty      bool
	ProtocolID    int64
	FeatureSpec   []byte
	ModelFamily   string
	Hyperparams   []byte
	Seed          int32
	ParentRunID   pgtype.Int8
	Hypothesis    pgtype.Text
	Status        string
	Metrics       []byte
	ErrorMessage  pgtype.Text
	StartedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	FeatureSpecID int64
}

type FeatureSpec struct {
	ID                 int64
	Name               string
	Version            int32
	RepresentationKind string
	Definition         []byte
	DefinitionSha256   string
	CreatedAt          pgtype.Timestamptz
}

type IngestionRun struct {
	ID           int64
	BatchKey     string
	Status       string
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	ErrorMessage pgtype.Text
	Summary      []byte
}

type Match struct {
	ID          int64
	NaturalKey  string
	Label       pgtype.Text
	Arm         string
	ScheduledAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	EventID     int64
	Status      string
	WeightClass string
}

type MatchCompetitor struct {
	MatchID   int64
	AthleteID int64
	Score     pgtype.Int4
	Result    pgtype.Text
}

type MatchVideo struct {
	MatchID        int64
	YoutubeVideoID string
}

type RunFeatureRow struct {
	RunID         int64
	FoldIndex     int32
	MatchID       int64
	Role          string
	Payload       []byte
	PayloadSha256 string
}

type RunInputManifest struct {
	RunID          int64
	CutoffPolicy   []byte
	DataSummary    []byte
	ManifestSha256 string
}

type RunModel struct {
	RunID  int64
	Params []byte
}

type RunPrediction struct {
	RunID     int64
	MatchID   int64
	AthleteID int64
	PWin      float64
}

type Source struct {
	ID          int64
	SourceType  string
	ExternalID  string
	Url         string
	Title       pgtype.Text
	PublishedAt pgtype.Timestamptz
	RawPayload  []byte
	CreatedAt   pgtype.Timestamptz
}

type SourceExtraction struct {
	ID            int64
	SourceID      int64
	MatchID       int64
	Provider      string
	Model         string
	PromptVersion string
	Status        string
	ExtractedAt   pgtype.Timestamptz
	RawResponse   []byte
	Usage         []byte
	ErrorMessage  pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type VCompletedMatch struct {
	MatchID     int64
	EventID     int64
	ScheduledAt pgtype.Timestamptz
	Arm         string
	WeightClass string
	AthleteAID  int64
	AthleteBID  int64
	ResultA     pgtype.Text
}
