// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Athlete struct {
	ID            int64
	CanonicalName string
	CreatedAt     pgtype.Timestamptz
}

type Claim struct {
	ID                 int64
	SourceID           int64
	MatchID            int64
	ClaimText          string
	TimestampSeconds   pgtype.Int4
	Speaker            pgtype.Text
	Confidence         pgtype.Text
	Relevance          pgtype.Text
	ObservedAt         pgtype.Timestamptz
	ExtractedAt        pgtype.Timestamptz
	ExtractionModel    pgtype.Text
	RawPayload         []byte
	CreatedAt          pgtype.Timestamptz
	SourceExtractionID pgtype.Int8
}

type ClaimSubject struct {
	ClaimID   int64
	AthleteID int64
}

type Event struct {
	ID        int64
	Slug      string
	Promoter  string
	Name      string
	HeldOn    pgtype.Date
	CreatedAt pgtype.Timestamptz
}

type IngestionRun struct {
	ID           int64
	BatchKey     string
	Status       string
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	ErrorMessage pgtype.Text
	Summary      []byte
}

type Match struct {
	ID          int64
	NaturalKey  string
	Label       pgtype.Text
	Arm         string
	ScheduledAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	EventID     int64
	Status      string
}

type MatchCompetitor struct {
	MatchID   int64
	AthleteID int64
	Score     pgtype.Int4
	Result    pgtype.Text
}

type Source struct {
	ID          int64
	SourceType  string
	ExternalID  string
	Url         string
	Title       pgtype.Text
	PublishedAt pgtype.Timestamptz
	RawPayload  []byte
	CreatedAt   pgtype.Timestamptz
}

type SourceExtraction struct {
	ID            int64
	SourceID      int64
	MatchID       int64
	Provider      string
	Model         string
	PromptVersion string
	Status        string
	ExtractedAt   pgtype.Timestamptz
	RawResponse   []byte
	Usage         []byte
	ErrorMessage  pgtype.Text
	CreatedAt     pgtype.Timestamptz
}
